// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace DALChatGPT.Models;

public partial class LanguageType
{
    public int Id { get; set; }

    public string? LanguageName { get; set; }

    public DateTime? CreatedDate { get; set; }

    public bool? IsDeleted { get; set; }

    public virtual ICollection<MailTemplate> MailTemplates { get; set; } = new List<MailTemplate>();
}