// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace DALChatGPT.Models;

public partial class MailTemplate
{
    public int Id { get; set; }

    public string? MailText { get; set; }

    public int ParentId { get; set; }

    public int? LanguageId { get; set; }

    public DateTime? CreatedDate { get; set; }

    public bool? IsDeleted { get; set; }

    public virtual LanguageType? Language { get; set; }
}